### ISSUE TITLE
Help @JsonIgnore

### ISSUE THREAD

**Issue by DamianMiara** [zpi-pwr-grupa1/cinema-pro#1]
Po mojej stronie JsonIgnore nie pozwala na skompilowanie projektu. Próba rozwiązania problemu wymaga wskazania zależności.

**Comment by Macioosio** [comment]
Zaciągnij zmiany z pom.xml i załaduj na nowo dependancies. Problem jest taki, że @JsonIgnore jest z biblioteki, którą musiałem dodać do zależności.
